const plotDataRawAvatar3 = [
    {
        "plot_no":  "1",
        "plot_size":  "401.00",
        "extent_sq_mtrs":  "479.59",
        "facing":  "North-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "2",
        "plot_size":  "267.00",
        "extent_sq_mtrs":  "319.33",
        "facing":  "North",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "3",
        "plot_size":  "269.00",
        "extent_sq_mtrs":  "321.72",
        "facing":  "North",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "4",
        "plot_size":  "270.00",
        "extent_sq_mtrs":  "322.92",
        "facing":  "North",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "5",
        "plot_size":  "272.00",
        "extent_sq_mtrs":  "325.31",
        "facing":  "North",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "6",
        "plot_size":  "464.00",
        "extent_sq_mtrs":  "554.94",
        "facing":  "North (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "7",
        "plot_size":  "224.00",
        "extent_sq_mtrs":  "267.90",
        "facing":  "East (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "8",
        "plot_size":  "180.00",
        "extent_sq_mtrs":  "215.28",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "9",
        "plot_size":  "180.00",
        "extent_sq_mtrs":  "215.28",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "10",
        "plot_size":  "180.00",
        "extent_sq_mtrs":  "215.28",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "11",
        "plot_size":  "300.00",
        "extent_sq_mtrs":  "358.80",
        "facing":  "North-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "12",
        "plot_size":  "275.00",
        "extent_sq_mtrs":  "328.90",
        "facing":  "North-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "13",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 1",
        "classification":  "Land Owner 1",
        "share_of":  "M/s. VEDANT SPA \u0026 RESORTS PRIVATE LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "14",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "15",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "16",
        "plot_size":  "271.00",
        "extent_sq_mtrs":  "324.11",
        "facing":  "West (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "17",
        "plot_size":  "214.00",
        "extent_sq_mtrs":  "255.94",
        "facing":  "East (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "18",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "19",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "20",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "21",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "22",
        "plot_size":  "275.00",
        "extent_sq_mtrs":  "328.90",
        "facing":  "North-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "23",
        "plot_size":  "275.00",
        "extent_sq_mtrs":  "328.90",
        "facing":  "North-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "24",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "25",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "26",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "27",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "28",
        "plot_size":  "276.00",
        "extent_sq_mtrs":  "330.09",
        "facing":  "West (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "29",
        "plot_size":  "192.00",
        "extent_sq_mtrs":  "229.63",
        "facing":  "East (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "30",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "31",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "32",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "33",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "34",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "35",
        "plot_size":  "244.00",
        "extent_sq_mtrs":  "291.82",
        "facing":  "North-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "36",
        "plot_size":  "244.00",
        "extent_sq_mtrs":  "291.82",
        "facing":  "North-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "37",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "38",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "39",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "40",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "41",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "42",
        "plot_size":  "203.00",
        "extent_sq_mtrs":  "242.79",
        "facing":  "West (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "43",
        "plot_size":  "156.00",
        "extent_sq_mtrs":  "186.57",
        "facing":  "East (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "44",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "45",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "46",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "47",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "48",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "49",
        "plot_size":  "244.00",
        "extent_sq_mtrs":  "291.82",
        "facing":  "North-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "50",
        "plot_size":  "244.00",
        "extent_sq_mtrs":  "291.82",
        "facing":  "North-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "51",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "52",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "53",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "54",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "55",
        "plot_size":  "277.00",
        "extent_sq_mtrs":  "331.29",
        "facing":  "West (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "56",
        "plot_size":  "230.00",
        "extent_sq_mtrs":  "275.08",
        "facing":  "East (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "57",
        "plot_size":  "146.61",
        "extent_sq_mtrs":  "175.35",
        "facing":  "East",
        "plot_status":  "SOLD",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "58",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "59",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "SOLD",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "60",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "SOLD",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "61",
        "plot_size":  "244.00",
        "extent_sq_mtrs":  "291.82",
        "facing":  "North-East",
        "plot_status":  "SOLD",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "62",
        "plot_size":  "244.00",
        "extent_sq_mtrs":  "291.82",
        "facing":  "West (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "63",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "64",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "65",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "SOLD",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "66",
        "plot_size":  "268.00",
        "extent_sq_mtrs":  "320.53",
        "facing":  "North-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "67",
        "plot_size":  "217.00",
        "extent_sq_mtrs":  "259.53",
        "facing":  "South-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 4",
        "classification":  "Land Owner 4",
        "share_of":  "KAKARLA GOVINDA REDDY",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "68",
        "plot_size":  "183.00",
        "extent_sq_mtrs":  "218.87",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "69",
        "plot_size":  "183.00",
        "extent_sq_mtrs":  "218.87",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "70",
        "plot_size":  "183.00",
        "extent_sq_mtrs":  "218.87",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "71",
        "plot_size":  "183.00",
        "extent_sq_mtrs":  "218.87",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "72",
        "plot_size":  "183.00",
        "extent_sq_mtrs":  "218.87",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "73",
        "plot_size":  "183.00",
        "extent_sq_mtrs":  "218.87",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 4",
        "classification":  "Land Owner 4",
        "share_of":  "KAKARLA GOVINDA REDDY",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "74",
        "plot_size":  "183.00",
        "extent_sq_mtrs":  "218.87",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 4",
        "classification":  "Land Owner 4",
        "share_of":  "KAKARLA GOVINDA REDDY",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "75",
        "plot_size":  "183.00",
        "extent_sq_mtrs":  "218.87",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 4",
        "classification":  "Land Owner 4",
        "share_of":  "KAKARLA GOVINDA REDDY",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "76",
        "plot_size":  "188.00",
        "extent_sq_mtrs":  "224.85",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 4",
        "classification":  "Land Owner 4",
        "share_of":  "KAKARLA GOVINDA REDDY",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "77",
        "plot_size":  "168.91",
        "extent_sq_mtrs":  "202.01",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 4",
        "classification":  "Land Owner 4",
        "share_of":  "KAKARLA GOVINDA REDDY",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "78",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 4",
        "classification":  "Land Owner 4",
        "share_of":  "KAKARLA GOVINDA REDDY",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "79",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 4",
        "classification":  "Land Owner 4",
        "share_of":  "KAKARLA GOVINDA REDDY",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "80",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "81",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "82",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "83",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "84",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "85",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "86",
        "plot_size":  "195.00",
        "extent_sq_mtrs":  "233.22",
        "facing":  "South-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "87",
        "plot_size":  "195.00",
        "extent_sq_mtrs":  "233.22",
        "facing":  "South-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "88",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "89",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "90",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "91",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "92",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "93",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "94",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "95",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "96",
        "plot_size":  "167.00",
        "extent_sq_mtrs":  "199.73",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "97",
        "plot_size":  "166.00",
        "extent_sq_mtrs":  "198.53",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "98",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "99",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "100",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "101",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "102",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "103",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "104",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "105",
        "plot_size":  "165.00",
        "extent_sq_mtrs":  "197.34",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "106",
        "plot_size":  "195.00",
        "extent_sq_mtrs":  "233.22",
        "facing":  "South-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "107",
        "plot_size":  "173.00",
        "extent_sq_mtrs":  "206.91",
        "facing":  "South-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "108",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "109",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "110",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "111",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "112",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "113",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "114",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "115",
        "plot_size":  "146.66",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "116",
        "plot_size":  "153.00",
        "extent_sq_mtrs":  "182.99",
        "facing":  "East (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "117",
        "plot_size":  "171.00",
        "extent_sq_mtrs":  "204.51",
        "facing":  "West (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "118",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "119",
        "plot_size":  "146.66",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "120",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "121",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "122",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "123",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "124",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "125",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "126",
        "plot_size":  "173.00",
        "extent_sq_mtrs":  "206.91",
        "facing":  "South-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "127",
        "plot_size":  "173.00",
        "extent_sq_mtrs":  "206.91",
        "facing":  "South-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "128",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "129",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "130",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "131",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "132",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "133",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "134",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "135",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "136",
        "plot_size":  "204.00",
        "extent_sq_mtrs":  "243.98",
        "facing":  "East (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "137",
        "plot_size":  "243.00",
        "extent_sq_mtrs":  "290.63",
        "facing":  "West (Cross)",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "138",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "139",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "140",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "141",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "142",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "143",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "144",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "145",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "146",
        "plot_size":  "173.00",
        "extent_sq_mtrs":  "206.91",
        "facing":  "South-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "147",
        "plot_size":  "173.00",
        "extent_sq_mtrs":  "206.91",
        "facing":  "South-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "148",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "149",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "150",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "151",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "152",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "153",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "154",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "155",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "156",
        "plot_size":  "221.00",
        "extent_sq_mtrs":  "264.31",
        "facing":  "North-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "157",
        "plot_size":  "221.00",
        "extent_sq_mtrs":  "264.31",
        "facing":  "North-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "158",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "159",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "160",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "161",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "162",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "163",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "164",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "165",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "166",
        "plot_size":  "173.00",
        "extent_sq_mtrs":  "206.91",
        "facing":  "South-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "167",
        "plot_size":  "173.00",
        "extent_sq_mtrs":  "206.91",
        "facing":  "South-East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "168",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "169",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "East",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "170",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "171",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "172",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "173",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "174",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "175",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "176",
        "plot_size":  "221.48",
        "extent_sq_mtrs":  "264.89",
        "facing":  "North-East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "177",
        "plot_size":  "221.48",
        "extent_sq_mtrs":  "264.89",
        "facing":  "North-West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "178",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "179",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "180",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "181",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "182",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "183",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "184",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "185",
        "plot_size":  "147.00",
        "extent_sq_mtrs":  "175.81",
        "facing":  "West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "186",
        "plot_size":  "173.00",
        "extent_sq_mtrs":  "206.91",
        "facing":  "South-West",
        "plot_status":  "AVAILABLE",
        "raw_status":  "Open",
        "customer_name":  "",
        "reference_name":  "Land Owner 2",
        "classification":  "Land Owner 2",
        "share_of":  "M/s. INFINITY SECURITY PAPERS LIMITED",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "187",
        "plot_size":  "185.94",
        "extent_sq_mtrs":  "222.38",
        "facing":  "South-West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "188",
        "plot_size":  "159.29",
        "extent_sq_mtrs":  "190.51",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "189",
        "plot_size":  "160.46",
        "extent_sq_mtrs":  "191.90",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "190",
        "plot_size":  "159.37",
        "extent_sq_mtrs":  "190.61",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "191",
        "plot_size":  "150.84",
        "extent_sq_mtrs":  "180.41",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "192",
        "plot_size":  "146.63",
        "extent_sq_mtrs":  "175.37",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "193",
        "plot_size":  "146.63",
        "extent_sq_mtrs":  "175.37",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "194",
        "plot_size":  "173.37",
        "extent_sq_mtrs":  "207.34",
        "facing":  "South-East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "195",
        "plot_size":  "173.37",
        "extent_sq_mtrs":  "207.34",
        "facing":  "South-West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "196",
        "plot_size":  "146.65",
        "extent_sq_mtrs":  "175.39",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "197",
        "plot_size":  "146.65",
        "extent_sq_mtrs":  "175.39",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "198",
        "plot_size":  "153.30",
        "extent_sq_mtrs":  "183.35",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "199",
        "plot_size":  "162.50",
        "extent_sq_mtrs":  "194.35",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "200",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.41",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "201",
        "plot_size":  "146.64",
        "extent_sq_mtrs":  "175.39",
        "facing":  "East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "202",
        "plot_size":  "173.30",
        "extent_sq_mtrs":  "207.27",
        "facing":  "South-East",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "203",
        "plot_size":  "173.32",
        "extent_sq_mtrs":  "207.29",
        "facing":  "South-West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "204",
        "plot_size":  "146.69",
        "extent_sq_mtrs":  "175.44",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "205",
        "plot_size":  "146.67",
        "extent_sq_mtrs":  "175.42",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "206",
        "plot_size":  "166.31",
        "extent_sq_mtrs":  "198.91",
        "facing":  "West",
        "plot_status":  "MORTGAGE",
        "raw_status":  "Mortgage",
        "customer_name":  "",
        "reference_name":  "Developer",
        "classification":  "Developer",
        "share_of":  "M/s. GEETHIKA INFRA DEVELOPERS",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    },
    {
        "plot_no":  "Total",
        "plot_size":  "35530.44",
        "extent_sq_mtrs":  "42494.05",
        "facing":  "",
        "plot_status":  "AVAILABLE",
        "raw_status":  "",
        "customer_name":  "",
        "reference_name":  "",
        "classification":  "",
        "share_of":  "",
        "dim_north":  "-",
        "dim_south":  "-",
        "dim_east":  "-",
        "dim_west":  "-"
    }
];